default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: shorten_url_app_development
  host: db
  password: root
  username: postgres

test:
  <<: *default
  database: shorten_url_app_test
  host: db
  password: root
  username: postgres

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { '' } %>
