inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance

Metrics/MethodLength:
  Max: 100

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Metrics/ClassLength:
  Enabled: false
